/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IamRouteRouteImport } from './routes/iam/route'
import { Route as IamLoginRouteImport } from './routes/iam/login'
import { Route as IamRegisterRouteImport } from './routes/iam/register'
import { Route as IamVerifyEmailRouteImport } from './routes/iam/verify-email'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IamRouteRoute = IamRouteRouteImport.update({
  id: '/iam',
  path: '/iam',
  getParentRoute: () => rootRouteImport,
} as any)
const IamLoginRoute = IamLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => IamRouteRoute,
} as any)
const IamRegisterRoute = IamRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => IamRouteRoute,
} as any)
const IamVerifyEmailRoute = IamVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => IamRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iam': typeof IamRouteRouteWithChildren
  '/iam/login': typeof IamLoginRoute
  '/iam/register': typeof IamRegisterRoute
  '/iam/verify-email': typeof IamVerifyEmailRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iam': typeof IamRouteRouteWithChildren
  '/iam/login': typeof IamLoginRoute
  '/iam/register': typeof IamRegisterRoute
  '/iam/verify-email': typeof IamVerifyEmailRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iam': typeof IamRouteRouteWithChildren
  '/iam/login': typeof IamLoginRoute
  '/iam/register': typeof IamRegisterRoute
  '/iam/verify-email': typeof IamVerifyEmailRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iam'
    | '/iam/login'
    | '/iam/register'
    | '/iam/verify-email'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iam'
    | '/iam/login'
    | '/iam/register'
    | '/iam/verify-email'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/iam'
    | '/iam/login'
    | '/iam/register'
    | '/iam/verify-email'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IamRouteRoute: typeof IamRouteRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam': {
      id: '/iam'
      path: '/iam'
      fullPath: '/iam'
      preLoaderRoute: typeof IamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam/login': {
      id: '/iam/login'
      path: '/login'
      fullPath: '/iam/login'
      preLoaderRoute: typeof IamLoginRouteImport
      parentRoute: typeof IamRouteRoute
    }
    '/iam/register': {
      id: '/iam/register'
      path: '/register'
      fullPath: '/iam/register'
      preLoaderRoute: typeof IamRegisterRouteImport
      parentRoute: typeof IamRouteRoute
    }
    '/iam/verify-email': {
      id: '/iam/verify-email'
      path: '/verify-email'
      fullPath: '/iam/verify-email'
      preLoaderRoute: typeof IamVerifyEmailRouteImport
      parentRoute: typeof IamRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IamRouteRouteChildren {
  IamLoginRoute: typeof IamLoginRoute
  IamRegisterRoute: typeof IamRegisterRoute
  IamVerifyEmailRoute: typeof IamVerifyEmailRoute
}

const IamRouteRouteChildren: IamRouteRouteChildren = {
  IamLoginRoute: IamLoginRoute,
  IamRegisterRoute: IamRegisterRoute,
  IamVerifyEmailRoute: IamVerifyEmailRoute,
}

const IamRouteRouteWithChildren = IamRouteRoute._addFileChildren(
  IamRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IamRouteRoute: IamRouteRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
